version: 2.1

orbs: 
  browser-tools: circleci/browser-tools@1.3.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16.10-browsers

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: sudo rm -rf node_modules

      - run: npm install
      - run:
          name: run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test:
    jobs:
      - test